package com.akun.elibrary.bean;

import java.util.Date;
import java.util.UUID;

public class Borrowinfo {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.borrowInfo.borrowid
	 * @ibatorgenerated  Fri Apr 13 14:14:56 CST 2012
	 */
	private Integer borrowid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.borrowInfo.sid
	 * @ibatorgenerated  Fri Apr 13 14:14:56 CST 2012
	 */
	private Integer sid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.borrowInfo.borrowTime
	 * @ibatorgenerated  Fri Apr 13 14:14:56 CST 2012
	 */
	private String borrowtime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.borrowInfo.expectedReturnTime
	 * @ibatorgenerated  Fri Apr 13 14:14:56 CST 2012
	 */
	private String expectedreturntime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.borrowInfo.borrownum
	 * @ibatorgenerated  Fri Apr 13 14:14:56 CST 2012
	 */
	private Integer borrownum;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.borrowInfo.borrowid
	 * @return  the value of dbo.borrowInfo.borrowid
	 * @ibatorgenerated  Fri Apr 13 14:14:56 CST 2012
	 */
	public Integer getBorrowid() {
		return borrowid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.borrowInfo.borrowid
	 * @param borrowid  the value for dbo.borrowInfo.borrowid
	 * @ibatorgenerated  Fri Apr 13 14:14:56 CST 2012
	 */
	public void setBorrowid(Integer borrowid) {
		this.borrowid = borrowid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.borrowInfo.sid
	 * @return  the value of dbo.borrowInfo.sid
	 * @ibatorgenerated  Fri Apr 13 14:14:56 CST 2012
	 */
	public Integer getSid() {
		return sid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.borrowInfo.sid
	 * @param sid  the value for dbo.borrowInfo.sid
	 * @ibatorgenerated  Fri Apr 13 14:14:56 CST 2012
	 */
	public void setSid(Integer sid) {
		this.sid = sid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.borrowInfo.borrowTime
	 * @return  the value of dbo.borrowInfo.borrowTime
	 * @ibatorgenerated  Fri Apr 13 14:14:56 CST 2012
	 */
	public String getBorrowtime() {
		return borrowtime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.borrowInfo.borrowTime
	 * @param borrowtime  the value for dbo.borrowInfo.borrowTime
	 * @ibatorgenerated  Fri Apr 13 14:14:56 CST 2012
	 */
	public void setBorrowtime(String borrowtime) {
		this.borrowtime = borrowtime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.borrowInfo.expectedReturnTime
	 * @return  the value of dbo.borrowInfo.expectedReturnTime
	 * @ibatorgenerated  Fri Apr 13 14:14:56 CST 2012
	 */
	public String getExpectedreturntime() {
		return expectedreturntime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.borrowInfo.expectedReturnTime
	 * @param expectedreturntime  the value for dbo.borrowInfo.expectedReturnTime
	 * @ibatorgenerated  Fri Apr 13 14:14:56 CST 2012
	 */
	public void setExpectedreturntime(String expectedreturntime) {
		this.expectedreturntime = expectedreturntime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.borrowInfo.borrownum
	 * @return  the value of dbo.borrowInfo.borrownum
	 * @ibatorgenerated  Fri Apr 13 14:14:56 CST 2012
	 */
	public Integer getBorrownum() {
		return borrownum;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.borrowInfo.borrownum
	 * @param borrownum  the value for dbo.borrowInfo.borrownum
	 * @ibatorgenerated  Fri Apr 13 14:14:56 CST 2012
	 */
	public void setBorrownum(Integer borrownum) {
		this.borrownum = borrownum;
	}
}