package com.akun.elibrary.bean;

public class Classes {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.classes.classNumber
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	private String classnumber;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.classes.classLeader
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	private String classleader;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.classes.cname
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	private String cname;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.classes.classNumber
	 * @return  the value of dbo.classes.classNumber
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public String getClassnumber() {
		return classnumber;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.classes.classNumber
	 * @param classnumber  the value for dbo.classes.classNumber
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void setClassnumber(String classnumber) {
		this.classnumber = classnumber;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.classes.classLeader
	 * @return  the value of dbo.classes.classLeader
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public String getClassleader() {
		return classleader;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.classes.classLeader
	 * @param classleader  the value for dbo.classes.classLeader
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void setClassleader(String classleader) {
		this.classleader = classleader;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.classes.cname
	 * @return  the value of dbo.classes.cname
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public String getCname() {
		return cname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.classes.cname
	 * @param cname  the value for dbo.classes.cname
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void setCname(String cname) {
		this.cname = cname;
	}
}