package com.akun.elibrary.bean;

public class Libuser {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.libuser.userid
	 * @ibatorgenerated  Thu Apr 05 20:03:40 CST 2012
	 */
	private Integer userid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.libuser.username
	 * @ibatorgenerated  Thu Apr 05 20:03:40 CST 2012
	 */
	private String username;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.libuser.userpwd
	 * @ibatorgenerated  Thu Apr 05 20:03:40 CST 2012
	 */
	private String userpwd;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.libuser.realname
	 * @ibatorgenerated  Thu Apr 05 20:03:40 CST 2012
	 */
	private String realname;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.libuser.tel
	 * @ibatorgenerated  Thu Apr 05 20:03:40 CST 2012
	 */
	private String tel;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.libuser.email
	 * @ibatorgenerated  Thu Apr 05 20:03:40 CST 2012
	 */
	private String email;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.libuser.userid
	 * @return  the value of dbo.libuser.userid
	 * @ibatorgenerated  Thu Apr 05 20:03:40 CST 2012
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.libuser.userid
	 * @param userid  the value for dbo.libuser.userid
	 * @ibatorgenerated  Thu Apr 05 20:03:40 CST 2012
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.libuser.username
	 * @return  the value of dbo.libuser.username
	 * @ibatorgenerated  Thu Apr 05 20:03:40 CST 2012
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.libuser.username
	 * @param username  the value for dbo.libuser.username
	 * @ibatorgenerated  Thu Apr 05 20:03:40 CST 2012
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.libuser.userpwd
	 * @return  the value of dbo.libuser.userpwd
	 * @ibatorgenerated  Thu Apr 05 20:03:40 CST 2012
	 */
	public String getUserpwd() {
		return userpwd;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.libuser.userpwd
	 * @param userpwd  the value for dbo.libuser.userpwd
	 * @ibatorgenerated  Thu Apr 05 20:03:40 CST 2012
	 */
	public void setUserpwd(String userpwd) {
		this.userpwd = userpwd;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.libuser.realname
	 * @return  the value of dbo.libuser.realname
	 * @ibatorgenerated  Thu Apr 05 20:03:40 CST 2012
	 */
	public String getRealname() {
		return realname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.libuser.realname
	 * @param realname  the value for dbo.libuser.realname
	 * @ibatorgenerated  Thu Apr 05 20:03:40 CST 2012
	 */
	public void setRealname(String realname) {
		this.realname = realname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.libuser.tel
	 * @return  the value of dbo.libuser.tel
	 * @ibatorgenerated  Thu Apr 05 20:03:40 CST 2012
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.libuser.tel
	 * @param tel  the value for dbo.libuser.tel
	 * @ibatorgenerated  Thu Apr 05 20:03:40 CST 2012
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.libuser.email
	 * @return  the value of dbo.libuser.email
	 * @ibatorgenerated  Thu Apr 05 20:03:40 CST 2012
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.libuser.email
	 * @param email  the value for dbo.libuser.email
	 * @ibatorgenerated  Thu Apr 05 20:03:40 CST 2012
	 */
	public void setEmail(String email) {
		this.email = email;
	}
}