package com.akun.elibrary.bean;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class LiteratureExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table dbo.literature
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table dbo.literature
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literature
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public LiteratureExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literature
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	protected LiteratureExample(LiteratureExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literature
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literature
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literature
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literature
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literature
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literature
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literature
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table dbo.literature
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andLiteratureidIsNull() {
			addCriterion("literatureid is null");
			return this;
		}

		public Criteria andLiteratureidIsNotNull() {
			addCriterion("literatureid is not null");
			return this;
		}

		public Criteria andLiteratureidEqualTo(Integer value) {
			addCriterion("literatureid =", value, "literatureid");
			return this;
		}
		public Criteria andLiteratureidEqualTo(String stringIds) {
			addCriterion("literatureid =", stringIds, "literatureid");
			return this;
		}

		public Criteria andLiteratureidNotEqualTo(Integer value) {
			addCriterion("literatureid <>", value, "literatureid");
			return this;
		}

		public Criteria andLiteratureidGreaterThan(Integer value) {
			addCriterion("literatureid >", value, "literatureid");
			return this;
		}

		public Criteria andLiteratureidGreaterThanOrEqualTo(Integer value) {
			addCriterion("literatureid >=", value, "literatureid");
			return this;
		}

		public Criteria andLiteratureidLessThan(Integer value) {
			addCriterion("literatureid <", value, "literatureid");
			return this;
		}

		public Criteria andLiteratureidLessThanOrEqualTo(Integer value) {
			addCriterion("literatureid <=", value, "literatureid");
			return this;
		}

		public Criteria andLiteratureidIn(List values) {
			addCriterion("literatureid in", values, "literatureid");
			return this;
		}

		public Criteria andLiteratureidNotIn(List values) {
			addCriterion("literatureid not in", values, "literatureid");
			return this;
		}

		public Criteria andLiteratureidBetween(Integer value1, Integer value2) {
			addCriterion("literatureid between", value1, value2, "literatureid");
			return this;
		}

		public Criteria andLiteratureidNotBetween(Integer value1, Integer value2) {
			addCriterion("literatureid not between", value1, value2, "literatureid");
			return this;
		}

		public Criteria andCategoryidIsNull() {
			addCriterion("categoryid is null");
			return this;
		}

		public Criteria andCategoryidIsNotNull() {
			addCriterion("categoryid is not null");
			return this;
		}

		public Criteria andCategoryidEqualTo(Integer value) {
			addCriterion("categoryid =", value, "categoryid");
			return this;
		}

		public Criteria andCategoryidNotEqualTo(Integer value) {
			addCriterion("categoryid <>", value, "categoryid");
			return this;
		}

		public Criteria andCategoryidGreaterThan(Integer value) {
			addCriterion("categoryid >", value, "categoryid");
			return this;
		}

		public Criteria andCategoryidGreaterThanOrEqualTo(Integer value) {
			addCriterion("categoryid >=", value, "categoryid");
			return this;
		}

		public Criteria andCategoryidLessThan(Integer value) {
			addCriterion("categoryid <", value, "categoryid");
			return this;
		}

		public Criteria andCategoryidLessThanOrEqualTo(Integer value) {
			addCriterion("categoryid <=", value, "categoryid");
			return this;
		}

		public Criteria andCategoryidIn(List values) {
			addCriterion("categoryid in", values, "categoryid");
			return this;
		}

		public Criteria andCategoryidNotIn(List values) {
			addCriterion("categoryid not in", values, "categoryid");
			return this;
		}

		public Criteria andCategoryidBetween(Integer value1, Integer value2) {
			addCriterion("categoryid between", value1, value2, "categoryid");
			return this;
		}

		public Criteria andCategoryidNotBetween(Integer value1, Integer value2) {
			addCriterion("categoryid not between", value1, value2, "categoryid");
			return this;
		}

		public Criteria andLiteraturenameIsNull() {
			addCriterion("literatureName is null");
			return this;
		}

		public Criteria andLiteraturenameIsNotNull() {
			addCriterion("literatureName is not null");
			return this;
		}

		public Criteria andLiteraturenameEqualTo(String value) {
			addCriterion("literatureName =", value, "literaturename");
			return this;
		}

		public Criteria andLiteraturenameNotEqualTo(String value) {
			addCriterion("literatureName <>", value, "literaturename");
			return this;
		}

		public Criteria andLiteraturenameGreaterThan(String value) {
			addCriterion("literatureName >", value, "literaturename");
			return this;
		}

		public Criteria andLiteraturenameGreaterThanOrEqualTo(String value) {
			addCriterion("literatureName >=", value, "literaturename");
			return this;
		}

		public Criteria andLiteraturenameLessThan(String value) {
			addCriterion("literatureName <", value, "literaturename");
			return this;
		}

		public Criteria andLiteraturenameLessThanOrEqualTo(String value) {
			addCriterion("literatureName <=", value, "literaturename");
			return this;
		}

		public Criteria andLiteraturenameLike(String value) {
			addCriterion("literatureName like", value, "literaturename");
			return this;
		}

		public Criteria andLiteraturenameNotLike(String value) {
			addCriterion("literatureName not like", value, "literaturename");
			return this;
		}

		public Criteria andLiteraturenameIn(List values) {
			addCriterion("literatureName in", values, "literaturename");
			return this;
		}

		public Criteria andLiteraturenameNotIn(List values) {
			addCriterion("literatureName not in", values, "literaturename");
			return this;
		}

		public Criteria andLiteraturenameBetween(String value1, String value2) {
			addCriterion("literatureName between", value1, value2, "literaturename");
			return this;
		}

		public Criteria andLiteraturenameNotBetween(String value1, String value2) {
			addCriterion("literatureName not between", value1, value2, "literaturename");
			return this;
		}

		public Criteria andAuthorIsNull() {
			addCriterion("author is null");
			return this;
		}

		public Criteria andAuthorIsNotNull() {
			addCriterion("author is not null");
			return this;
		}

		public Criteria andAuthorEqualTo(String value) {
			addCriterion("author =", value, "author");
			return this;
		}

		public Criteria andAuthorNotEqualTo(String value) {
			addCriterion("author <>", value, "author");
			return this;
		}

		public Criteria andAuthorGreaterThan(String value) {
			addCriterion("author >", value, "author");
			return this;
		}

		public Criteria andAuthorGreaterThanOrEqualTo(String value) {
			addCriterion("author >=", value, "author");
			return this;
		}

		public Criteria andAuthorLessThan(String value) {
			addCriterion("author <", value, "author");
			return this;
		}

		public Criteria andAuthorLessThanOrEqualTo(String value) {
			addCriterion("author <=", value, "author");
			return this;
		}

		public Criteria andAuthorLike(String value) {
			addCriterion("author like", value, "author");
			return this;
		}

		public Criteria andAuthorNotLike(String value) {
			addCriterion("author not like", value, "author");
			return this;
		}

		public Criteria andAuthorIn(List values) {
			addCriterion("author in", values, "author");
			return this;
		}

		public Criteria andAuthorNotIn(List values) {
			addCriterion("author not in", values, "author");
			return this;
		}

		public Criteria andAuthorBetween(String value1, String value2) {
			addCriterion("author between", value1, value2, "author");
			return this;
		}

		public Criteria andAuthorNotBetween(String value1, String value2) {
			addCriterion("author not between", value1, value2, "author");
			return this;
		}

		public Criteria andPressIsNull() {
			addCriterion("press is null");
			return this;
		}

		public Criteria andPressIsNotNull() {
			addCriterion("press is not null");
			return this;
		}

		public Criteria andPressEqualTo(String value) {
			addCriterion("press =", value, "press");
			return this;
		}

		public Criteria andPressNotEqualTo(String value) {
			addCriterion("press <>", value, "press");
			return this;
		}

		public Criteria andPressGreaterThan(String value) {
			addCriterion("press >", value, "press");
			return this;
		}

		public Criteria andPressGreaterThanOrEqualTo(String value) {
			addCriterion("press >=", value, "press");
			return this;
		}

		public Criteria andPressLessThan(String value) {
			addCriterion("press <", value, "press");
			return this;
		}

		public Criteria andPressLessThanOrEqualTo(String value) {
			addCriterion("press <=", value, "press");
			return this;
		}

		public Criteria andPressLike(String value) {
			addCriterion("press like", value, "press");
			return this;
		}

		public Criteria andPressNotLike(String value) {
			addCriterion("press not like", value, "press");
			return this;
		}

		public Criteria andPressIn(List values) {
			addCriterion("press in", values, "press");
			return this;
		}

		public Criteria andPressNotIn(List values) {
			addCriterion("press not in", values, "press");
			return this;
		}

		public Criteria andPressBetween(String value1, String value2) {
			addCriterion("press between", value1, value2, "press");
			return this;
		}

		public Criteria andPressNotBetween(String value1, String value2) {
			addCriterion("press not between", value1, value2, "press");
			return this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("price is null");
			return this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("price is not null");
			return this;
		}

		public Criteria andPriceEqualTo(Double value) {
			addCriterion("price =", value, "price");
			return this;
		}

		public Criteria andPriceNotEqualTo(Double value) {
			addCriterion("price <>", value, "price");
			return this;
		}

		public Criteria andPriceGreaterThan(Double value) {
			addCriterion("price >", value, "price");
			return this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(Double value) {
			addCriterion("price >=", value, "price");
			return this;
		}

		public Criteria andPriceLessThan(Double value) {
			addCriterion("price <", value, "price");
			return this;
		}

		public Criteria andPriceLessThanOrEqualTo(Double value) {
			addCriterion("price <=", value, "price");
			return this;
		}

		public Criteria andPriceIn(List values) {
			addCriterion("price in", values, "price");
			return this;
		}

		public Criteria andPriceNotIn(List values) {
			addCriterion("price not in", values, "price");
			return this;
		}

		public Criteria andPriceBetween(Double value1, Double value2) {
			addCriterion("price between", value1, value2, "price");
			return this;
		}

		public Criteria andPriceNotBetween(Double value1, Double value2) {
			addCriterion("price not between", value1, value2, "price");
			return this;
		}

		public Criteria andNumIsNull() {
			addCriterion("num is null");
			return this;
		}

		public Criteria andNumIsNotNull() {
			addCriterion("num is not null");
			return this;
		}

		public Criteria andNumEqualTo(Integer value) {
			addCriterion("num =", value, "num");
			return this;
		}

		public Criteria andNumNotEqualTo(Integer value) {
			addCriterion("num <>", value, "num");
			return this;
		}

		public Criteria andNumGreaterThan(Integer value) {
			addCriterion("num >", value, "num");
			return this;
		}

		public Criteria andNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("num >=", value, "num");
			return this;
		}

		public Criteria andNumLessThan(Integer value) {
			addCriterion("num <", value, "num");
			return this;
		}

		public Criteria andNumLessThanOrEqualTo(Integer value) {
			addCriterion("num <=", value, "num");
			return this;
		}

		public Criteria andNumIn(List values) {
			addCriterion("num in", values, "num");
			return this;
		}

		public Criteria andNumNotIn(List values) {
			addCriterion("num not in", values, "num");
			return this;
		}

		public Criteria andNumBetween(Integer value1, Integer value2) {
			addCriterion("num between", value1, value2, "num");
			return this;
		}

		public Criteria andNumNotBetween(Integer value1, Integer value2) {
			addCriterion("num not between", value1, value2, "num");
			return this;
		}

		public Criteria andLindexIsNull() {
			addCriterion("lindex is null");
			return this;
		}

		public Criteria andLindexIsNotNull() {
			addCriterion("lindex is not null");
			return this;
		}

		public Criteria andLindexEqualTo(String value) {
			addCriterion("lindex =", value, "lindex");
			return this;
		}

		public Criteria andLindexNotEqualTo(String value) {
			addCriterion("lindex <>", value, "lindex");
			return this;
		}

		public Criteria andLindexGreaterThan(String value) {
			addCriterion("lindex >", value, "lindex");
			return this;
		}

		public Criteria andLindexGreaterThanOrEqualTo(String value) {
			addCriterion("lindex >=", value, "lindex");
			return this;
		}

		public Criteria andLindexLessThan(String value) {
			addCriterion("lindex <", value, "lindex");
			return this;
		}

		public Criteria andLindexLessThanOrEqualTo(String value) {
			addCriterion("lindex <=", value, "lindex");
			return this;
		}

		public Criteria andLindexLike(String value) {
			addCriterion("lindex like", value, "lindex");
			return this;
		}

		public Criteria andLindexNotLike(String value) {
			addCriterion("lindex not like", value, "lindex");
			return this;
		}

		public Criteria andLindexIn(List values) {
			addCriterion("lindex in", values, "lindex");
			return this;
		}

		public Criteria andLindexNotIn(List values) {
			addCriterion("lindex not in", values, "lindex");
			return this;
		}

		public Criteria andLindexBetween(String value1, String value2) {
			addCriterion("lindex between", value1, value2, "lindex");
			return this;
		}

		public Criteria andLindexNotBetween(String value1, String value2) {
			addCriterion("lindex not between", value1, value2, "lindex");
			return this;
		}
	}
}