package com.akun.elibrary.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class StudentExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table dbo.student
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table dbo.student
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.student
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public StudentExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.student
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	protected StudentExample(StudentExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.student
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.student
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.student
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.student
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.student
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.student
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.student
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table dbo.student
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andSidIsNull() {
			addCriterion("sid is null");
			return this;
		}

		public Criteria andSidIsNotNull() {
			addCriterion("sid is not null");
			return this;
		}

		public Criteria andSidEqualTo(Integer value) {
			addCriterion("sid =", value, "sid");
			return this;
		}

		public Criteria andSidNotEqualTo(Integer value) {
			addCriterion("sid <>", value, "sid");
			return this;
		}

		public Criteria andSidGreaterThan(Integer value) {
			addCriterion("sid >", value, "sid");
			return this;
		}

		public Criteria andSidGreaterThanOrEqualTo(Integer value) {
			addCriterion("sid >=", value, "sid");
			return this;
		}

		public Criteria andSidLessThan(Integer value) {
			addCriterion("sid <", value, "sid");
			return this;
		}

		public Criteria andSidLessThanOrEqualTo(Integer value) {
			addCriterion("sid <=", value, "sid");
			return this;
		}

		public Criteria andSidIn(List values) {
			addCriterion("sid in", values, "sid");
			return this;
		}

		public Criteria andSidNotIn(List values) {
			addCriterion("sid not in", values, "sid");
			return this;
		}

		public Criteria andSidBetween(Integer value1, Integer value2) {
			addCriterion("sid between", value1, value2, "sid");
			return this;
		}

		public Criteria andSidNotBetween(Integer value1, Integer value2) {
			addCriterion("sid not between", value1, value2, "sid");
			return this;
		}

		public Criteria andSnumberIsNull() {
			addCriterion("snumber is null");
			return this;
		}

		public Criteria andSnumberIsNotNull() {
			addCriterion("snumber is not null");
			return this;
		}

		public Criteria andSnumberEqualTo(String value) {
			addCriterion("snumber =", value, "snumber");
			return this;
		}

		public Criteria andSnumberNotEqualTo(String value) {
			addCriterion("snumber <>", value, "snumber");
			return this;
		}

		public Criteria andSnumberGreaterThan(String value) {
			addCriterion("snumber >", value, "snumber");
			return this;
		}

		public Criteria andSnumberGreaterThanOrEqualTo(String value) {
			addCriterion("snumber >=", value, "snumber");
			return this;
		}

		public Criteria andSnumberLessThan(String value) {
			addCriterion("snumber <", value, "snumber");
			return this;
		}

		public Criteria andSnumberLessThanOrEqualTo(String value) {
			addCriterion("snumber <=", value, "snumber");
			return this;
		}

		public Criteria andSnumberLike(String value) {
			addCriterion("snumber like", value, "snumber");
			return this;
		}

		public Criteria andSnumberNotLike(String value) {
			addCriterion("snumber not like", value, "snumber");
			return this;
		}

		public Criteria andSnumberIn(List values) {
			addCriterion("snumber in", values, "snumber");
			return this;
		}

		public Criteria andSnumberNotIn(List values) {
			addCriterion("snumber not in", values, "snumber");
			return this;
		}

		public Criteria andSnumberBetween(String value1, String value2) {
			addCriterion("snumber between", value1, value2, "snumber");
			return this;
		}

		public Criteria andSnumberNotBetween(String value1, String value2) {
			addCriterion("snumber not between", value1, value2, "snumber");
			return this;
		}

		public Criteria andSnameIsNull() {
			addCriterion("sname is null");
			return this;
		}

		public Criteria andSnameIsNotNull() {
			addCriterion("sname is not null");
			return this;
		}

		public Criteria andSnameEqualTo(String value) {
			addCriterion("sname =", value, "sname");
			return this;
		}

		public Criteria andSnameNotEqualTo(String value) {
			addCriterion("sname <>", value, "sname");
			return this;
		}

		public Criteria andSnameGreaterThan(String value) {
			addCriterion("sname >", value, "sname");
			return this;
		}

		public Criteria andSnameGreaterThanOrEqualTo(String value) {
			addCriterion("sname >=", value, "sname");
			return this;
		}

		public Criteria andSnameLessThan(String value) {
			addCriterion("sname <", value, "sname");
			return this;
		}

		public Criteria andSnameLessThanOrEqualTo(String value) {
			addCriterion("sname <=", value, "sname");
			return this;
		}

		public Criteria andSnameLike(String value) {
			addCriterion("sname like", value, "sname");
			return this;
		}

		public Criteria andSnameNotLike(String value) {
			addCriterion("sname not like", value, "sname");
			return this;
		}

		public Criteria andSnameIn(List values) {
			addCriterion("sname in", values, "sname");
			return this;
		}

		public Criteria andSnameNotIn(List values) {
			addCriterion("sname not in", values, "sname");
			return this;
		}

		public Criteria andSnameBetween(String value1, String value2) {
			addCriterion("sname between", value1, value2, "sname");
			return this;
		}

		public Criteria andSnameNotBetween(String value1, String value2) {
			addCriterion("sname not between", value1, value2, "sname");
			return this;
		}

		public Criteria andSexIsNull() {
			addCriterion("sex is null");
			return this;
		}

		public Criteria andSexIsNotNull() {
			addCriterion("sex is not null");
			return this;
		}

		public Criteria andSexEqualTo(Short value) {
			addCriterion("sex =", value, "sex");
			return this;
		}

		public Criteria andSexNotEqualTo(Short value) {
			addCriterion("sex <>", value, "sex");
			return this;
		}

		public Criteria andSexGreaterThan(Short value) {
			addCriterion("sex >", value, "sex");
			return this;
		}

		public Criteria andSexGreaterThanOrEqualTo(Short value) {
			addCriterion("sex >=", value, "sex");
			return this;
		}

		public Criteria andSexLessThan(Short value) {
			addCriterion("sex <", value, "sex");
			return this;
		}

		public Criteria andSexLessThanOrEqualTo(Short value) {
			addCriterion("sex <=", value, "sex");
			return this;
		}

		public Criteria andSexIn(List values) {
			addCriterion("sex in", values, "sex");
			return this;
		}

		public Criteria andSexNotIn(List values) {
			addCriterion("sex not in", values, "sex");
			return this;
		}

		public Criteria andSexBetween(Short value1, Short value2) {
			addCriterion("sex between", value1, value2, "sex");
			return this;
		}

		public Criteria andSexNotBetween(Short value1, Short value2) {
			addCriterion("sex not between", value1, value2, "sex");
			return this;
		}

		public Criteria andBirthdateIsNull() {
			addCriterion("birthdate is null");
			return this;
		}

		public Criteria andBirthdateIsNotNull() {
			addCriterion("birthdate is not null");
			return this;
		}

		public Criteria andBirthdateEqualTo(Date value) {
			addCriterion("birthdate =", value, "birthdate");
			return this;
		}

		public Criteria andBirthdateNotEqualTo(Date value) {
			addCriterion("birthdate <>", value, "birthdate");
			return this;
		}

		public Criteria andBirthdateGreaterThan(Date value) {
			addCriterion("birthdate >", value, "birthdate");
			return this;
		}

		public Criteria andBirthdateGreaterThanOrEqualTo(Date value) {
			addCriterion("birthdate >=", value, "birthdate");
			return this;
		}

		public Criteria andBirthdateLessThan(Date value) {
			addCriterion("birthdate <", value, "birthdate");
			return this;
		}

		public Criteria andBirthdateLessThanOrEqualTo(Date value) {
			addCriterion("birthdate <=", value, "birthdate");
			return this;
		}

		public Criteria andBirthdateIn(List values) {
			addCriterion("birthdate in", values, "birthdate");
			return this;
		}

		public Criteria andBirthdateNotIn(List values) {
			addCriterion("birthdate not in", values, "birthdate");
			return this;
		}

		public Criteria andBirthdateBetween(Date value1, Date value2) {
			addCriterion("birthdate between", value1, value2, "birthdate");
			return this;
		}

		public Criteria andBirthdateNotBetween(Date value1, Date value2) {
			addCriterion("birthdate not between", value1, value2, "birthdate");
			return this;
		}

		public Criteria andTelIsNull() {
			addCriterion("tel is null");
			return this;
		}

		public Criteria andTelIsNotNull() {
			addCriterion("tel is not null");
			return this;
		}

		public Criteria andTelEqualTo(String value) {
			addCriterion("tel =", value, "tel");
			return this;
		}

		public Criteria andTelNotEqualTo(String value) {
			addCriterion("tel <>", value, "tel");
			return this;
		}

		public Criteria andTelGreaterThan(String value) {
			addCriterion("tel >", value, "tel");
			return this;
		}

		public Criteria andTelGreaterThanOrEqualTo(String value) {
			addCriterion("tel >=", value, "tel");
			return this;
		}

		public Criteria andTelLessThan(String value) {
			addCriterion("tel <", value, "tel");
			return this;
		}

		public Criteria andTelLessThanOrEqualTo(String value) {
			addCriterion("tel <=", value, "tel");
			return this;
		}

		public Criteria andTelLike(String value) {
			addCriterion("tel like", value, "tel");
			return this;
		}

		public Criteria andTelNotLike(String value) {
			addCriterion("tel not like", value, "tel");
			return this;
		}

		public Criteria andTelIn(List values) {
			addCriterion("tel in", values, "tel");
			return this;
		}

		public Criteria andTelNotIn(List values) {
			addCriterion("tel not in", values, "tel");
			return this;
		}

		public Criteria andTelBetween(String value1, String value2) {
			addCriterion("tel between", value1, value2, "tel");
			return this;
		}

		public Criteria andTelNotBetween(String value1, String value2) {
			addCriterion("tel not between", value1, value2, "tel");
			return this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("address is null");
			return this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("address is not null");
			return this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("address =", value, "address");
			return this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("address <>", value, "address");
			return this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("address >", value, "address");
			return this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("address >=", value, "address");
			return this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("address <", value, "address");
			return this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("address <=", value, "address");
			return this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("address like", value, "address");
			return this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("address not like", value, "address");
			return this;
		}

		public Criteria andAddressIn(List values) {
			addCriterion("address in", values, "address");
			return this;
		}

		public Criteria andAddressNotIn(List values) {
			addCriterion("address not in", values, "address");
			return this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("address between", value1, value2, "address");
			return this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("address not between", value1, value2, "address");
			return this;
		}

		public Criteria andZipcodeIsNull() {
			addCriterion("zipcode is null");
			return this;
		}

		public Criteria andZipcodeIsNotNull() {
			addCriterion("zipcode is not null");
			return this;
		}

		public Criteria andZipcodeEqualTo(String value) {
			addCriterion("zipcode =", value, "zipcode");
			return this;
		}

		public Criteria andZipcodeNotEqualTo(String value) {
			addCriterion("zipcode <>", value, "zipcode");
			return this;
		}

		public Criteria andZipcodeGreaterThan(String value) {
			addCriterion("zipcode >", value, "zipcode");
			return this;
		}

		public Criteria andZipcodeGreaterThanOrEqualTo(String value) {
			addCriterion("zipcode >=", value, "zipcode");
			return this;
		}

		public Criteria andZipcodeLessThan(String value) {
			addCriterion("zipcode <", value, "zipcode");
			return this;
		}

		public Criteria andZipcodeLessThanOrEqualTo(String value) {
			addCriterion("zipcode <=", value, "zipcode");
			return this;
		}

		public Criteria andZipcodeLike(String value) {
			addCriterion("zipcode like", value, "zipcode");
			return this;
		}

		public Criteria andZipcodeNotLike(String value) {
			addCriterion("zipcode not like", value, "zipcode");
			return this;
		}

		public Criteria andZipcodeIn(List values) {
			addCriterion("zipcode in", values, "zipcode");
			return this;
		}

		public Criteria andZipcodeNotIn(List values) {
			addCriterion("zipcode not in", values, "zipcode");
			return this;
		}

		public Criteria andZipcodeBetween(String value1, String value2) {
			addCriterion("zipcode between", value1, value2, "zipcode");
			return this;
		}

		public Criteria andZipcodeNotBetween(String value1, String value2) {
			addCriterion("zipcode not between", value1, value2, "zipcode");
			return this;
		}

		public Criteria andPwdIsNull() {
			addCriterion("pwd is null");
			return this;
		}

		public Criteria andPwdIsNotNull() {
			addCriterion("pwd is not null");
			return this;
		}

		public Criteria andPwdEqualTo(String value) {
			addCriterion("pwd =", value, "pwd");
			return this;
		}

		public Criteria andPwdNotEqualTo(String value) {
			addCriterion("pwd <>", value, "pwd");
			return this;
		}

		public Criteria andPwdGreaterThan(String value) {
			addCriterion("pwd >", value, "pwd");
			return this;
		}

		public Criteria andPwdGreaterThanOrEqualTo(String value) {
			addCriterion("pwd >=", value, "pwd");
			return this;
		}

		public Criteria andPwdLessThan(String value) {
			addCriterion("pwd <", value, "pwd");
			return this;
		}

		public Criteria andPwdLessThanOrEqualTo(String value) {
			addCriterion("pwd <=", value, "pwd");
			return this;
		}

		public Criteria andPwdLike(String value) {
			addCriterion("pwd like", value, "pwd");
			return this;
		}

		public Criteria andPwdNotLike(String value) {
			addCriterion("pwd not like", value, "pwd");
			return this;
		}

		public Criteria andPwdIn(List values) {
			addCriterion("pwd in", values, "pwd");
			return this;
		}

		public Criteria andPwdNotIn(List values) {
			addCriterion("pwd not in", values, "pwd");
			return this;
		}

		public Criteria andPwdBetween(String value1, String value2) {
			addCriterion("pwd between", value1, value2, "pwd");
			return this;
		}

		public Criteria andPwdNotBetween(String value1, String value2) {
			addCriterion("pwd not between", value1, value2, "pwd");
			return this;
		}

		public Criteria andClassnumberIsNull() {
			addCriterion("classNumber is null");
			return this;
		}

		public Criteria andClassnumberIsNotNull() {
			addCriterion("classNumber is not null");
			return this;
		}

		public Criteria andClassnumberEqualTo(String value) {
			addCriterion("classNumber =", value, "classnumber");
			return this;
		}

		public Criteria andClassnumberNotEqualTo(String value) {
			addCriterion("classNumber <>", value, "classnumber");
			return this;
		}

		public Criteria andClassnumberGreaterThan(String value) {
			addCriterion("classNumber >", value, "classnumber");
			return this;
		}

		public Criteria andClassnumberGreaterThanOrEqualTo(String value) {
			addCriterion("classNumber >=", value, "classnumber");
			return this;
		}

		public Criteria andClassnumberLessThan(String value) {
			addCriterion("classNumber <", value, "classnumber");
			return this;
		}

		public Criteria andClassnumberLessThanOrEqualTo(String value) {
			addCriterion("classNumber <=", value, "classnumber");
			return this;
		}

		public Criteria andClassnumberLike(String value) {
			addCriterion("classNumber like", value, "classnumber");
			return this;
		}

		public Criteria andClassnumberNotLike(String value) {
			addCriterion("classNumber not like", value, "classnumber");
			return this;
		}

		public Criteria andClassnumberIn(List values) {
			addCriterion("classNumber in", values, "classnumber");
			return this;
		}

		public Criteria andClassnumberNotIn(List values) {
			addCriterion("classNumber not in", values, "classnumber");
			return this;
		}

		public Criteria andClassnumberBetween(String value1, String value2) {
			addCriterion("classNumber between", value1, value2, "classnumber");
			return this;
		}

		public Criteria andClassnumberNotBetween(String value1, String value2) {
			addCriterion("classNumber not between", value1, value2, "classnumber");
			return this;
		}
	}
}