package com.akun.elibrary.dao;

import com.akun.elibrary.bean.Borrowinfo;
import com.akun.elibrary.bean.BorrowinfoExample;
import java.util.List;

public interface BorrowinfoDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.borrowInfo
	 * @ibatorgenerated  Fri Apr 13 14:14:56 CST 2012
	 */
	int countByExample(BorrowinfoExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.borrowInfo
	 * @ibatorgenerated  Fri Apr 13 14:14:56 CST 2012
	 */
	int deleteByExample(BorrowinfoExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.borrowInfo
	 * @ibatorgenerated  Fri Apr 13 14:14:56 CST 2012
	 */
	int deleteByPrimaryKey(Integer borrowid);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.borrowInfo
	 * @ibatorgenerated  Fri Apr 13 14:14:56 CST 2012
	 */
	void insert(Borrowinfo record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.borrowInfo
	 * @ibatorgenerated  Fri Apr 13 14:14:56 CST 2012
	 */
	void insertSelective(Borrowinfo record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.borrowInfo
	 * @ibatorgenerated  Fri Apr 13 14:14:56 CST 2012
	 */
	List selectByExample(BorrowinfoExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.borrowInfo
	 * @ibatorgenerated  Fri Apr 13 14:14:56 CST 2012
	 */
	Borrowinfo selectByPrimaryKey(Integer borrowid);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.borrowInfo
	 * @ibatorgenerated  Fri Apr 13 14:14:56 CST 2012
	 */
	int updateByExampleSelective(Borrowinfo record, BorrowinfoExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.borrowInfo
	 * @ibatorgenerated  Fri Apr 13 14:14:56 CST 2012
	 */
	int updateByExample(Borrowinfo record, BorrowinfoExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.borrowInfo
	 * @ibatorgenerated  Fri Apr 13 14:14:56 CST 2012
	 */
	int updateByPrimaryKeySelective(Borrowinfo record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.borrowInfo
	 * @ibatorgenerated  Fri Apr 13 14:14:56 CST 2012
	 */
	int updateByPrimaryKey(Borrowinfo record);
}