package com.akun.elibrary.dao;

import com.akun.elibrary.bean.Category;
import com.akun.elibrary.bean.CategoryExample;
import java.util.List;

public interface CategoryDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.category
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	int countByExample(CategoryExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.category
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	int deleteByExample(CategoryExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.category
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	int deleteByPrimaryKey(Integer categoryid);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.category
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	void insert(Category record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.category
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	void insertSelective(Category record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.category
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	List selectByExample(CategoryExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.category
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	Category selectByPrimaryKey(Integer categoryid);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.category
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	int updateByExampleSelective(Category record, CategoryExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.category
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	int updateByExample(Category record, CategoryExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.category
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	int updateByPrimaryKeySelective(Category record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.category
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	int updateByPrimaryKey(Category record);
}