package com.akun.elibrary.dao;

import com.akun.elibrary.bean.Libuser;
import com.akun.elibrary.bean.LibuserExample;
import java.util.List;

public interface LibuserDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.libuser
	 * @ibatorgenerated  Thu Apr 05 20:03:40 CST 2012
	 */
	int countByExample(LibuserExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.libuser
	 * @ibatorgenerated  Thu Apr 05 20:03:40 CST 2012
	 */
	int deleteByExample(LibuserExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.libuser
	 * @ibatorgenerated  Thu Apr 05 20:03:40 CST 2012
	 */
	int deleteByPrimaryKey(Integer userid);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.libuser
	 * @ibatorgenerated  Thu Apr 05 20:03:40 CST 2012
	 */
	void insert(Libuser record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.libuser
	 * @ibatorgenerated  Thu Apr 05 20:03:40 CST 2012
	 */
	void insertSelective(Libuser record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.libuser
	 * @ibatorgenerated  Thu Apr 05 20:03:40 CST 2012
	 */
	List selectByExample(LibuserExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.libuser
	 * @ibatorgenerated  Thu Apr 05 20:03:40 CST 2012
	 */
	Libuser selectByPrimaryKey(Integer userid);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.libuser
	 * @ibatorgenerated  Thu Apr 05 20:03:40 CST 2012
	 */
	int updateByExampleSelective(Libuser record, LibuserExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.libuser
	 * @ibatorgenerated  Thu Apr 05 20:03:40 CST 2012
	 */
	int updateByExample(Libuser record, LibuserExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.libuser
	 * @ibatorgenerated  Thu Apr 05 20:03:40 CST 2012
	 */
	int updateByPrimaryKeySelective(Libuser record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.libuser
	 * @ibatorgenerated  Thu Apr 05 20:03:40 CST 2012
	 */
	int updateByPrimaryKey(Libuser record);
}