package com.akun.elibrary.dao;

import com.akun.elibrary.bean.Student;
import com.akun.elibrary.bean.StudentExample;
import java.util.List;

public interface StudentDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.student
	 * @ibatorgenerated  Tue Apr 03 13:58:22 CST 2012
	 */
	int countByExample(StudentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.student
	 * @ibatorgenerated  Tue Apr 03 13:58:22 CST 2012
	 */
	int deleteByExample(StudentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.student
	 * @ibatorgenerated  Tue Apr 03 13:58:22 CST 2012
	 */
	int deleteByPrimaryKey(Integer sid);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.student
	 * @ibatorgenerated  Tue Apr 03 13:58:22 CST 2012
	 */
	void insert(Student record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.student
	 * @ibatorgenerated  Tue Apr 03 13:58:22 CST 2012
	 */
	void insertSelective(Student record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.student
	 * @ibatorgenerated  Tue Apr 03 13:58:22 CST 2012
	 */
	List selectByExample(StudentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.student
	 * @ibatorgenerated  Tue Apr 03 13:58:22 CST 2012
	 */
	Student selectByPrimaryKey(Integer sid);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.student
	 * @ibatorgenerated  Tue Apr 03 13:58:22 CST 2012
	 */
	int updateByExampleSelective(Student record, StudentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.student
	 * @ibatorgenerated  Tue Apr 03 13:58:22 CST 2012
	 */
	int updateByExample(Student record, StudentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.student
	 * @ibatorgenerated  Tue Apr 03 13:58:22 CST 2012
	 */
	int updateByPrimaryKeySelective(Student record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.student
	 * @ibatorgenerated  Tue Apr 03 13:58:22 CST 2012
	 */
	int updateByPrimaryKey(Student record);

	List selectByExamplePage(StudentExample example,int skipResults,int limit);
}