package com.akun.elibrary.dao.imp;

import com.akun.elibrary.bean.Classes;
import com.akun.elibrary.bean.ClassesExample;
import com.akun.elibrary.dao.ClassesDAO;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ClassesDAOImpl extends SqlMapClientDaoSupport implements ClassesDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.classes
     *
     * @ibatorgenerated Tue Apr 03 13:58:22 CST 2012
     */
    public ClassesDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.classes
     *
     * @ibatorgenerated Tue Apr 03 13:58:22 CST 2012
     */
    public int countByExample(ClassesExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("dbo_classes.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.classes
     *
     * @ibatorgenerated Tue Apr 03 13:58:22 CST 2012
     */
    public int deleteByExample(ClassesExample example) {
        int rows = getSqlMapClientTemplate().delete("dbo_classes.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.classes
     *
     * @ibatorgenerated Tue Apr 03 13:58:22 CST 2012
     */
    public int deleteByPrimaryKey(String classnumber) {
        Classes key = new Classes();
        key.setClassnumber(classnumber);
        int rows = getSqlMapClientTemplate().delete("dbo_classes.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.classes
     *
     * @ibatorgenerated Tue Apr 03 13:58:22 CST 2012
     */
    public void insert(Classes record) {
        getSqlMapClientTemplate().insert("dbo_classes.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.classes
     *
     * @ibatorgenerated Tue Apr 03 13:58:22 CST 2012
     */
    public void insertSelective(Classes record) {
        getSqlMapClientTemplate().insert("dbo_classes.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.classes
     *
     * @ibatorgenerated Tue Apr 03 13:58:22 CST 2012
     */
    public List selectByExample(ClassesExample example) {
        List list = getSqlMapClientTemplate().queryForList("dbo_classes.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.classes
     *
     * @ibatorgenerated Tue Apr 03 13:58:22 CST 2012
     */
    public Classes selectByPrimaryKey(String classnumber) {
        Classes key = new Classes();
        key.setClassnumber(classnumber);
        Classes record = (Classes) getSqlMapClientTemplate().queryForObject("dbo_classes.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.classes
     *
     * @ibatorgenerated Tue Apr 03 13:58:22 CST 2012
     */
    public int updateByExampleSelective(Classes record, ClassesExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("dbo_classes.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.classes
     *
     * @ibatorgenerated Tue Apr 03 13:58:22 CST 2012
     */
    public int updateByExample(Classes record, ClassesExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("dbo_classes.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.classes
     *
     * @ibatorgenerated Tue Apr 03 13:58:22 CST 2012
     */
    public int updateByPrimaryKeySelective(Classes record) {
        int rows = getSqlMapClientTemplate().update("dbo_classes.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.classes
     *
     * @ibatorgenerated Tue Apr 03 13:58:22 CST 2012
     */
    public int updateByPrimaryKey(Classes record) {
        int rows = getSqlMapClientTemplate().update("dbo_classes.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table dbo.classes
     *
     * @ibatorgenerated Tue Apr 03 13:58:22 CST 2012
     */
    private static class UpdateByExampleParms extends ClassesExample {
        private Object record;

        public UpdateByExampleParms(Object record, ClassesExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}