package com.akun.elibrary.dao.imp;

import com.akun.elibrary.bean.Libuser;
import com.akun.elibrary.bean.LibuserExample;
import com.akun.elibrary.dao.LibuserDAO;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class LibuserDAOImpl extends SqlMapClientDaoSupport implements LibuserDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.libuser
     *
     * @ibatorgenerated Thu Apr 05 20:03:40 CST 2012
     */
    public LibuserDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.libuser
     *
     * @ibatorgenerated Thu Apr 05 20:03:40 CST 2012
     */
    public int countByExample(LibuserExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("dbo_libuser.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.libuser
     *
     * @ibatorgenerated Thu Apr 05 20:03:40 CST 2012
     */
    public int deleteByExample(LibuserExample example) {
        int rows = getSqlMapClientTemplate().delete("dbo_libuser.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.libuser
     *
     * @ibatorgenerated Thu Apr 05 20:03:40 CST 2012
     */
    public int deleteByPrimaryKey(Integer userid) {
        Libuser key = new Libuser();
        key.setUserid(userid);
        int rows = getSqlMapClientTemplate().delete("dbo_libuser.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.libuser
     *
     * @ibatorgenerated Thu Apr 05 20:03:40 CST 2012
     */
    public void insert(Libuser record) {
        getSqlMapClientTemplate().insert("dbo_libuser.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.libuser
     *
     * @ibatorgenerated Thu Apr 05 20:03:40 CST 2012
     */
    public void insertSelective(Libuser record) {
        getSqlMapClientTemplate().insert("dbo_libuser.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.libuser
     *
     * @ibatorgenerated Thu Apr 05 20:03:40 CST 2012
     */
    public List selectByExample(LibuserExample example) {
        List list = getSqlMapClientTemplate().queryForList("dbo_libuser.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.libuser
     *
     * @ibatorgenerated Thu Apr 05 20:03:40 CST 2012
     */
    public Libuser selectByPrimaryKey(Integer userid) {
        Libuser key = new Libuser();
        key.setUserid(userid);
        Libuser record = (Libuser) getSqlMapClientTemplate().queryForObject("dbo_libuser.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.libuser
     *
     * @ibatorgenerated Thu Apr 05 20:03:40 CST 2012
     */
    public int updateByExampleSelective(Libuser record, LibuserExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("dbo_libuser.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.libuser
     *
     * @ibatorgenerated Thu Apr 05 20:03:40 CST 2012
     */
    public int updateByExample(Libuser record, LibuserExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("dbo_libuser.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.libuser
     *
     * @ibatorgenerated Thu Apr 05 20:03:40 CST 2012
     */
    public int updateByPrimaryKeySelective(Libuser record) {
        int rows = getSqlMapClientTemplate().update("dbo_libuser.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.libuser
     *
     * @ibatorgenerated Thu Apr 05 20:03:40 CST 2012
     */
    public int updateByPrimaryKey(Libuser record) {
        int rows = getSqlMapClientTemplate().update("dbo_libuser.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table dbo.libuser
     *
     * @ibatorgenerated Thu Apr 05 20:03:40 CST 2012
     */
    private static class UpdateByExampleParms extends LibuserExample {
        private Object record;

        public UpdateByExampleParms(Object record, LibuserExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}