package com.akun.elibrary.dao.imp;

import com.akun.elibrary.bean.Student;
import com.akun.elibrary.bean.StudentExample;
import com.akun.elibrary.dao.StudentDAO;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class StudentDAOImpl extends SqlMapClientDaoSupport implements StudentDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.student
     *
     * @ibatorgenerated Sat Mar 31 21:06:35 CST 2012
     */
    public StudentDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.student
     *
     * @ibatorgenerated Sat Mar 31 21:06:35 CST 2012
     */
    public int countByExample(StudentExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("dbo_student.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.student
     *
     * @ibatorgenerated Sat Mar 31 21:06:35 CST 2012
     */
    public int deleteByExample(StudentExample example) {
        int rows = getSqlMapClientTemplate().delete("dbo_student.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.student
     *
     * @ibatorgenerated Sat Mar 31 21:06:35 CST 2012
     */
    public int deleteByPrimaryKey(Integer sid) {
        Student key = new Student();
        key.setSid(sid);
        int rows = getSqlMapClientTemplate().delete("dbo_student.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.student
     *
     * @ibatorgenerated Sat Mar 31 21:06:35 CST 2012
     */
    public void insert(Student record) {
        getSqlMapClientTemplate().insert("dbo_student.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.student
     *
     * @ibatorgenerated Sat Mar 31 21:06:35 CST 2012
     */
    public void insertSelective(Student record) {
        getSqlMapClientTemplate().insert("dbo_student.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.student
     *
     * @ibatorgenerated Sat Mar 31 21:06:35 CST 2012
     */
    public List selectByExample(StudentExample example) {
        List list = getSqlMapClientTemplate().queryForList("dbo_student.ibatorgenerated_selectByExample", example);
        return list;
    }
    /**
     * 
     * @author 杨宗昆<br>
     * 方法说明：分页查询学生信息<br>
     * @param
     * @return:
     */
    public List selectByExamplePage(StudentExample example,int skipResults,int limit){
    	List list = getSqlMapClientTemplate().queryForList("dbo_student.ibatorgenerated_selectByExample", example, skipResults, limit);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.student
     *
     * @ibatorgenerated Sat Mar 31 21:06:35 CST 2012
     */
    public Student selectByPrimaryKey(Integer sid) {
        Student key = new Student();
        key.setSid(sid);
        Student record = (Student) getSqlMapClientTemplate().queryForObject("dbo_student.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.student
     *
     * @ibatorgenerated Sat Mar 31 21:06:35 CST 2012
     */
    public int updateByExampleSelective(Student record, StudentExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("dbo_student.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.student
     *
     * @ibatorgenerated Sat Mar 31 21:06:35 CST 2012
     */
    public int updateByExample(Student record, StudentExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("dbo_student.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.student
     *
     * @ibatorgenerated Sat Mar 31 21:06:35 CST 2012
     */
    public int updateByPrimaryKeySelective(Student record) {
        int rows = getSqlMapClientTemplate().update("dbo_student.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.student
     *
     * @ibatorgenerated Sat Mar 31 21:06:35 CST 2012
     */
    public int updateByPrimaryKey(Student record) {
        int rows = getSqlMapClientTemplate().update("dbo_student.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table dbo.student
     *
     * @ibatorgenerated Sat Mar 31 21:06:35 CST 2012
     */
    private static class UpdateByExampleParms extends StudentExample {
        private Object record;

        public UpdateByExampleParms(Object record, StudentExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}