package com.akun.elibrary.dao.imp;

import com.akun.elibrary.bean.Borrowinfo;
import com.akun.elibrary.bean.BorrowinfoExample;
import com.akun.elibrary.dao.BorrowinfoDAO;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class BorrowinfoDAOImpl extends SqlMapClientDaoSupport implements BorrowinfoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.borrowInfo
     *
     * @ibatorgenerated Thu Apr 05 15:26:19 CST 2012
     */
    public BorrowinfoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.borrowInfo
     *
     * @ibatorgenerated Thu Apr 05 15:26:19 CST 2012
     */
    public int countByExample(BorrowinfoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("dbo_borrowInfo.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.borrowInfo
     *
     * @ibatorgenerated Thu Apr 05 15:26:19 CST 2012
     */
    public int deleteByExample(BorrowinfoExample example) {
        int rows = getSqlMapClientTemplate().delete("dbo_borrowInfo.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.borrowInfo
     *
     * @ibatorgenerated Thu Apr 05 15:26:19 CST 2012
     */
    public int deleteByPrimaryKey(Integer borrowid) {
        Borrowinfo key = new Borrowinfo();
        key.setBorrowid(borrowid);
        int rows = getSqlMapClientTemplate().delete("dbo_borrowInfo.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.borrowInfo
     *
     * @ibatorgenerated Thu Apr 05 15:26:19 CST 2012
     */
    public void insert(Borrowinfo record) {
        getSqlMapClientTemplate().insert("dbo_borrowInfo.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.borrowInfo
     *
     * @ibatorgenerated Thu Apr 05 15:26:19 CST 2012
     */
    public void insertSelective(Borrowinfo record) {
        getSqlMapClientTemplate().insert("dbo_borrowInfo.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.borrowInfo
     *
     * @ibatorgenerated Thu Apr 05 15:26:19 CST 2012
     */
    public List selectByExample(BorrowinfoExample example) {
        List list = getSqlMapClientTemplate().queryForList("dbo_borrowInfo.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.borrowInfo
     *
     * @ibatorgenerated Thu Apr 05 15:26:19 CST 2012
     */
    public Borrowinfo selectByPrimaryKey(Integer borrowid) {
        Borrowinfo key = new Borrowinfo();
        key.setBorrowid(borrowid);
        Borrowinfo record = (Borrowinfo) getSqlMapClientTemplate().queryForObject("dbo_borrowInfo.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.borrowInfo
     *
     * @ibatorgenerated Thu Apr 05 15:26:19 CST 2012
     */
    public int updateByExampleSelective(Borrowinfo record, BorrowinfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("dbo_borrowInfo.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.borrowInfo
     *
     * @ibatorgenerated Thu Apr 05 15:26:19 CST 2012
     */
    public int updateByExample(Borrowinfo record, BorrowinfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("dbo_borrowInfo.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.borrowInfo
     *
     * @ibatorgenerated Thu Apr 05 15:26:19 CST 2012
     */
    public int updateByPrimaryKeySelective(Borrowinfo record) {
        int rows = getSqlMapClientTemplate().update("dbo_borrowInfo.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table dbo.borrowInfo
     *
     * @ibatorgenerated Thu Apr 05 15:26:19 CST 2012
     */
    public int updateByPrimaryKey(Borrowinfo record) {
        int rows = getSqlMapClientTemplate().update("dbo_borrowInfo.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table dbo.borrowInfo
     *
     * @ibatorgenerated Thu Apr 05 15:26:19 CST 2012
     */
    private static class UpdateByExampleParms extends BorrowinfoExample {
        private Object record;

        public UpdateByExampleParms(Object record, BorrowinfoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}