package com.akun.elibrary.bean;

public class Category {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.category.categoryid
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	private Integer categoryid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.category.categoryName
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	private String categoryname;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.category.cindex
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	private String cindex;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.category.categoryid
	 * @return  the value of dbo.category.categoryid
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public Integer getCategoryid() {
		return categoryid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.category.categoryid
	 * @param categoryid  the value for dbo.category.categoryid
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void setCategoryid(Integer categoryid) {
		this.categoryid = categoryid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.category.categoryName
	 * @return  the value of dbo.category.categoryName
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public String getCategoryname() {
		return categoryname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.category.categoryName
	 * @param categoryname  the value for dbo.category.categoryName
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void setCategoryname(String categoryname) {
		this.categoryname = categoryname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.category.cindex
	 * @return  the value of dbo.category.cindex
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public String getCindex() {
		return cindex;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.category.cindex
	 * @param cindex  the value for dbo.category.cindex
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void setCindex(String cindex) {
		this.cindex = cindex;
	}
}