package com.akun.elibrary.bean;

public class LiteratureforborrowKey {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.literatureForBorrow.literatureid
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	private Integer literatureid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.literatureForBorrow.borrowid
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	private Integer borrowid;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.literatureForBorrow.literatureid
	 * @return  the value of dbo.literatureForBorrow.literatureid
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public Integer getLiteratureid() {
		return literatureid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.literatureForBorrow.literatureid
	 * @param literatureid  the value for dbo.literatureForBorrow.literatureid
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void setLiteratureid(Integer literatureid) {
		this.literatureid = literatureid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.literatureForBorrow.borrowid
	 * @return  the value of dbo.literatureForBorrow.borrowid
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public Integer getBorrowid() {
		return borrowid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.literatureForBorrow.borrowid
	 * @param borrowid  the value for dbo.literatureForBorrow.borrowid
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void setBorrowid(Integer borrowid) {
		this.borrowid = borrowid;
	}
}