package com.akun.elibrary.bean;

public class Literature {
    //添加属性outnum已借出数
	private Integer outnum;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.literature.literatureid
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	private Integer literatureid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.literature.categoryid
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	private Integer categoryid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.literature.literatureName
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	private String literaturename;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.literature.author
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	private String author;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.literature.press
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	private String press;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.literature.price
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	private Double price;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.literature.num
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	private Integer num;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.literature.lindex
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	private String lindex;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.literature.literatureid
	 * @return  the value of dbo.literature.literatureid
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public Integer getLiteratureid() {
		return literatureid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.literature.literatureid
	 * @param literatureid  the value for dbo.literature.literatureid
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void setLiteratureid(Integer literatureid) {
		this.literatureid = literatureid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.literature.categoryid
	 * @return  the value of dbo.literature.categoryid
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public Integer getCategoryid() {
		return categoryid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.literature.categoryid
	 * @param categoryid  the value for dbo.literature.categoryid
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void setCategoryid(Integer categoryid) {
		this.categoryid = categoryid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.literature.literatureName
	 * @return  the value of dbo.literature.literatureName
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public String getLiteraturename() {
		return literaturename;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.literature.literatureName
	 * @param literaturename  the value for dbo.literature.literatureName
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void setLiteraturename(String literaturename) {
		this.literaturename = literaturename;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.literature.author
	 * @return  the value of dbo.literature.author
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.literature.author
	 * @param author  the value for dbo.literature.author
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void setAuthor(String author) {
		this.author = author;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.literature.press
	 * @return  the value of dbo.literature.press
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public String getPress() {
		return press;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.literature.press
	 * @param press  the value for dbo.literature.press
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void setPress(String press) {
		this.press = press;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.literature.price
	 * @return  the value of dbo.literature.price
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.literature.price
	 * @param price  the value for dbo.literature.price
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.literature.num
	 * @return  the value of dbo.literature.num
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.literature.num
	 * @param num  the value for dbo.literature.num
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void setNum(Integer num) {
		this.num = num;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.literature.lindex
	 * @return  the value of dbo.literature.lindex
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public String getLindex() {
		return lindex;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.literature.lindex
	 * @param lindex  the value for dbo.literature.lindex
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void setLindex(String lindex) {
		this.lindex = lindex;
	}

	public Integer getOutnum() {
		return outnum;
	}

	public void setOutnum(Integer outnum) {
		this.outnum = outnum;
	}
	
}