package com.akun.elibrary.bean;

import java.util.Date;

public class Student {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.student.sid
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	private Integer sid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.student.snumber
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	private String snumber;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.student.sname
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	private String sname;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.student.sex
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	private Short sex;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.student.birthdate
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	private String birthdate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.student.tel
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	private String tel;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.student.address
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	private String address;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.student.zipcode
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	private String zipcode;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.student.pwd
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	private String pwd;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column dbo.student.classNumber
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	private String classnumber;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.student.sid
	 * @return  the value of dbo.student.sid
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public Integer getSid() {
		return sid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.student.sid
	 * @param sid  the value for dbo.student.sid
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void setSid(Integer sid) {
		this.sid = sid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.student.snumber
	 * @return  the value of dbo.student.snumber
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public String getSnumber() {
		return snumber;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.student.snumber
	 * @param snumber  the value for dbo.student.snumber
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void setSnumber(String snumber) {
		this.snumber = snumber;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.student.sname
	 * @return  the value of dbo.student.sname
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public String getSname() {
		return sname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.student.sname
	 * @param sname  the value for dbo.student.sname
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void setSname(String sname) {
		this.sname = sname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.student.sex
	 * @return  the value of dbo.student.sex
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public Short getSex() {
		return sex;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.student.sex
	 * @param sex  the value for dbo.student.sex
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void setSex(Short sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.student.birthdate
	 * @return  the value of dbo.student.birthdate
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public String getBirthdate() {
		return birthdate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.student.birthdate
	 * @param birthdate  the value for dbo.student.birthdate
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void setBirthdate(String birthdate) {
		this.birthdate = birthdate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.student.tel
	 * @return  the value of dbo.student.tel
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.student.tel
	 * @param tel  the value for dbo.student.tel
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.student.address
	 * @return  the value of dbo.student.address
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.student.address
	 * @param address  the value for dbo.student.address
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.student.zipcode
	 * @return  the value of dbo.student.zipcode
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public String getZipcode() {
		return zipcode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.student.zipcode
	 * @param zipcode  the value for dbo.student.zipcode
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.student.pwd
	 * @return  the value of dbo.student.pwd
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public String getPwd() {
		return pwd;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.student.pwd
	 * @param pwd  the value for dbo.student.pwd
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.student.classNumber
	 * @return  the value of dbo.student.classNumber
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public String getClassnumber() {
		return classnumber;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.student.classNumber
	 * @param classnumber  the value for dbo.student.classNumber
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	public void setClassnumber(String classnumber) {
		this.classnumber = classnumber;
	}
}