package com.akun.elibrary.dao;

import com.akun.elibrary.bean.Classes;
import com.akun.elibrary.bean.ClassesExample;
import java.util.List;

public interface ClassesDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.classes
	 * @ibatorgenerated  Tue Apr 03 13:58:22 CST 2012
	 */
	int countByExample(ClassesExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.classes
	 * @ibatorgenerated  Tue Apr 03 13:58:22 CST 2012
	 */
	int deleteByExample(ClassesExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.classes
	 * @ibatorgenerated  Tue Apr 03 13:58:22 CST 2012
	 */
	int deleteByPrimaryKey(String classnumber);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.classes
	 * @ibatorgenerated  Tue Apr 03 13:58:22 CST 2012
	 */
	void insert(Classes record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.classes
	 * @ibatorgenerated  Tue Apr 03 13:58:22 CST 2012
	 */
	void insertSelective(Classes record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.classes
	 * @ibatorgenerated  Tue Apr 03 13:58:22 CST 2012
	 */
	List selectByExample(ClassesExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.classes
	 * @ibatorgenerated  Tue Apr 03 13:58:22 CST 2012
	 */
	Classes selectByPrimaryKey(String classnumber);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.classes
	 * @ibatorgenerated  Tue Apr 03 13:58:22 CST 2012
	 */
	int updateByExampleSelective(Classes record, ClassesExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.classes
	 * @ibatorgenerated  Tue Apr 03 13:58:22 CST 2012
	 */
	int updateByExample(Classes record, ClassesExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.classes
	 * @ibatorgenerated  Tue Apr 03 13:58:22 CST 2012
	 */
	int updateByPrimaryKeySelective(Classes record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.classes
	 * @ibatorgenerated  Tue Apr 03 13:58:22 CST 2012
	 */
	int updateByPrimaryKey(Classes record);
}