package com.akun.elibrary.dao;

import com.akun.elibrary.bean.Literature;
import com.akun.elibrary.bean.LiteratureExample;
import java.util.List;

public interface LiteratureDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literature
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	int countByExample(LiteratureExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literature
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	int deleteByExample(LiteratureExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literature
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	int deleteByPrimaryKey(Integer literatureid);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literature
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	void insert(Literature record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literature
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	void insertSelective(Literature record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literature
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	List selectByExample(LiteratureExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literature
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	Literature selectByPrimaryKey(Integer literatureid);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literature
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	int updateByExampleSelective(Literature record, LiteratureExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literature
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	int updateByExample(Literature record, LiteratureExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literature
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	int updateByPrimaryKeySelective(Literature record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literature
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	int updateByPrimaryKey(Literature record);

	/**
	 * @author 杨宗昆<br>
	 * 方法说明：通过图书名搜索数据<br>
	 * @param
	 * @return:
	 */
	List<Literature> selectByKey(String key);
}